package com.thoongatechies.dmc.core.entity;

/**
 * Created by mages_000 on 6/1/2016.
 */
public interface Constants {

    String ACTIVE = "ACTIVE", IN_ACTIVE = "IN_ACTIVE", PROCESSED = "PROCESSED", PRE_NOTIFY = "PRE_NOTIFY", RETRY = "RETRY_SCHEDULED", FAILED = "FAILED", FAN_OUT = "FAN_OUT";
    String DEPENDENCY_SYSTEM_USER = "DEPENDENCY_SERVICE",SYSTEM_USER_NOTIFIER = "DEPENDENCY_SERVICE";
    String EVENT_STATUS_ACTIVE = ACTIVE, EVENT_STATUS_PROCESSED = PROCESSED;
    String RULE_STATUS_ACTIVE = ACTIVE, RULE_STATUS_INACTIVE = IN_ACTIVE;
    String RULE_STRATEGY_EXPRESSION_WITH_JSON_EQUALS = "EXPRESSION_WITH_JSON_EQUALS", DEFAULT_STRATEGY = RULE_STRATEGY_EXPRESSION_WITH_JSON_EQUALS;
    String CALLBACK_STATUS_ACTIVE = ACTIVE, CALLBACK_STATUS_IN_ACTIVE = IN_ACTIVE;

    String RULE_INSTANCE_STATUS_ACTIVE = ACTIVE, RULE_INSTANCE_STATUS_INACTIVE =IN_ACTIVE, RULE_INSTANCE_STATUS_PROCESSED = PROCESSED;

    String CALLBACK_INSTANCE_STATUS_ACTIVE = ACTIVE,
            CALLBACK_INSTANCE_STATUS_INACTIVE = IN_ACTIVE,
            CALLBACK_INSTANCE_STATUS_PROCESSED = PROCESSED,
            CALLBACK_INSTANCE_STATUS_RETRY = RETRY, CALLBACK_INSTANCE_STATUS_FAILED = FAILED;

    String EVENT_INSTANCE_STATUS_FAN_OUT = FAN_OUT, EVENT_INSTANCE_STATUS_PROCESSED = PROCESSED;

    String CALLBACK_ID = "CALLBACK_ID", RETRY_COUNT = "RETRY_COUNT", RETRY_TIME = "RETRY_TIME", RETRY_LIMIT = "RETRY_LIMIT";
    String HEADER_RETRY_TYPE = "RETRY_TYPE", HEADER_RETRY_DELAY = "RETRY_DELAY", HEADER_RETRY_LIMIT = "RETRY_LIMIT";

}
